---
apiVersion: v1
kind: Namespace
metadata:
  name: amq-broker
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker
  namespace: amq-broker
  labels:
    app: amq-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amq-broker
  template:
    metadata:
      labels:
        app: amq-broker
    spec:
      containers:
      - name: amq-broker
        image: registry.redhat.io/amq7/amq-broker:7.6
        imagePullPolicy: IfNotPresent
        env:
        - name: AMQ_USER
          value: admin
        - name: AMQ_PASSWORD
          value: admin
        - name: AMQ_PROTOCOL
          value: amqp,mqtt 
        ports:
         - containerPort: 61616 # general
         - containerPort: 8161  # web
         - containerPort: 5672  # amqp
         - containerPort: 1883  # mqtt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq-broker
  name: amq-web
  namespace: amq-broker
spec:
  ports:
  - port: 8161
    protocol: TCP
    targetPort: 8161
  selector:
    app:  amq-broker
  sessionAffinity: None
  type: ClusterIP
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq-broker
  name: mqtt
  namespace: amq-broker
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app:  amq-broker
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq-broker
  name: amqp
  namespace: amq-broker
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app:  amq-broker
  sessionAffinity: None
  type: NodePort

# Routes seem to be not working as of 4.10 rebase
# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   labels:
#     app: amq-broker
#   name: amq-broker
#   namespace: amq-broker
# spec:
#   host: amq-microshift.local
#   port:
#     targetPort: 8161
#   to:
#     kind: Service
#     name: amq-web
#     weight: 100
#   wildcardPolicy: None
