---
apiVersion: v1
kind: Namespace
metadata:
  name: app-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  namespace: app-web
  labels:
    app: app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - name: app-web
        image: quay.io/microshift/hello-world:latest
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 8080 # general
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-web
  name: app-web
  namespace: app-web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app:  app-web
  sessionAffinity: None
  type: ClusterIP

# re-enable once routes work again:
# Error from server (Forbidden): error when creating ".": routes.route.openshift.io "app-web" is forbidden: caches not synchronized
#---
#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  labels:
#    app: app-web
#  name: app-web
#spec:
#  host: app-interface.local
#  port:
#    targetPort: 8080
#  to:
#    kind: Service
#    name: app-web
#    weight: 100
#  wildcardPolicy: None