---
apiVersion: v1
kind: Namespace
metadata:
  name: app-plugin1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-plugin1
  namespace: app-plugin1
  labels:
    app: app-plugin1
    # the core app connects to the amqp / mqtt queues
    # and contains the core app logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-plugin1
  template:
    metadata:
      labels:
        app: app-plugin1
    spec:
      containers:
      - name: app-plugin1
        image: quay.io/submariner/nettest:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sleep"]
        args: ["3600"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-plugin1
  name: app-plugin1
  namespace: app-plugin1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app:  app-plugin1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: untrusted-plugin-to-api-only
  namespace: app-plugin1
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            app: app-logic
        podSelector:
          matchLabels:
            app: app-api
      ports:
        - protocol: TCP
          port: 8080


# Routes seem to be not working as of 4.10 rebase
# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   labels:
#     app: amq-broker
#   name: amq-broker
# spec:
#   host: amq-microshift.local
#   port:
#     targetPort: 8161
#   to:
#     kind: Service
#     name: amq-web
#     weight: 100
#   wildcardPolicy: None
