---
# configure-firewall default vars

firewall_services:
  - http
  - https
  - mdns

firewall_ports:
  - 80/tcp
  - 443/tcp
  - 2379/tcp
  - 3000/tcp
  - 5353/udp
  - 6443/tcp
  - 8080/tcp
  - 8082/tcp
  - 9091/tcp
  - 9100/tcp
  - 9256/tcp
  - 9537/tcp
  - 17001/tcp
  - 30000-32767/tcp
  - 30000-32767/udp

firewall_trusted_cidr:
  - 10.42.0.0/16
  - 169.254.169.1/32

