id = "ostree-copr"
name = "Copr repo for ostreerhel8 owned by walters"
type = "yum-baseurl"
url = "https://download.copr.fedorainfracloud.org/results/walters/ostreerhel8/centos-stream-8-x86_64/"
check_gpg = false
check_ssl = false
system = false
